### PR TITLE
Create Prime.c

### PR DESCRIPTION
**Pull request by dwivedyaakash**
A c program to check whether the entered number is prime or not.

### CODE REVIEW

**Comment by shreyansh-sawarn** [comment]
Can't you add something better? These really aren't worth it.

**Comment by shreyansh-sawarn** [comment]
I see you are into flutter and android. Go ahead and contribute something big @dwivedyaakash .

**Comment by dwivedyaakash** [comment]
Actually i'm a beginner and i am seaching for beginner friendly repos but didn't find any.

**Comment by shreyansh-sawarn** [comment]
Your profile doesn't seem like a beginner. Show off your 4 star hackerrank coding skills. I expect something better @dwivedyaakash

**Comment by shreyansh-sawarn** [comment]
See the thing is I can't allow easy PRs. You gotta push something good.

**Comment by dwivedyaakash** [comment]
Yeah i understand. Can you suggest something!

**Comment by shreyansh-sawarn** [comment]
Push something android or flutter related. Something like a mini project or something.

**Comment by shreyansh-sawarn** [comment]
I am closing this PR.

**Comment by dwivedyaakash** [comment]
Okay

**Pull request closed without merging**
